# Generated by Django 3.1.5 on 2021-01-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.IntegerField()),
                ('brand_name', models.CharField(max_length=255)),
                ('dosage_form', models.CharField(max_length=255)),
                ('generic_id', models.IntegerField()),
            ],
        ),
    ]
