# Generated by Django 3.1.5 on 2021-02-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.IntegerField()),
                ('generic_name', models.CharField(max_length=255)),
                ('monograph_link', models.CharField(max_length=255)),
                ('indication_description', models.CharField(max_length=255)),
            ],
        ),
    ]
