# Generated by Django 3.1.5 on 2021-02-02 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_generic'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
