# Generated by Django 3.1.5 on 2021-02-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_medicine_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='manufacturer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
