# Generated by Django 3.1.5 on 2021-02-04 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_medicine_manufacturer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generic',
            name='pharmacology_description',
            field=models.TextField(default='f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generic',
            name='therapeutic_class_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generic',
            name='indication_description',
            field=models.TextField(),
        ),
    ]
